version: '3.4'

services:
  lil.coustomers:
    image: ${DOCKER_REGISTRY-}lilcoustomers
    build:
      context: .
      dockerfile: Lil.Coustomers/Dockerfile

  lil.products:
    image: ${DOCKER_REGISTRY-}lilproducts
    build:
      context: .
      dockerfile: Lil.Products/Dockerfile


  lil.sales:
    image: ${DOCKER_REGISTRY-}lilsales
    build:
      context: .
      dockerfile: Lil.Sales/Dockerfile


  lil.search:
    image: ${DOCKER_REGISTRY-}lilsearch
    build:
      context: .
      dockerfile: Lil.Search/Dockerfile

    environment:
        - Services__Customers=http://lil.customers
        - Services__Products=http://lil.products
        - Services__Sales=http://lil.sales
